# This is a config for E2B sandbox template.
# You can use template ID (ph078lhr78iag3q6gk16) or template name (vibe-nextjs-imagollc) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-imagollc") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-imagollc") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-imagollc')

team_id = "aa358af7-73e3-416e-b638-e8888aad6b15"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-imagollc"
template_id = "ph078lhr78iag3q6gk16"
